### ISSUE TITLE
Check the variables in the RelayPrioritizer

### ISSUE THREAD

**Issue by pastly** [torproject/sbws#136]
During the switch to HTTPS, (the current plan is that) we're going to switch to picking a first hop as usual with the RelayPrioritizer, but then want to pick an exit separately using the first hop's bandwidth as a factor. We will no longer be measuring one relay at a time, and we will be getting results two at a time.

We'll be getting results for relays that the relay prioritizer hasn't returned (yet). And it won't be able to update it's idea of relay priority until it has worked all the way through its current list of relays to return. 

This means we might want to make it recalculate best priority more often.

**Comment by pastly** [comment]
I'm currently running with settings that essentially make it return 100 relays at a time.

It seems to take about 2 minutes to do its thing. I should check how often it has to calculate priority again when only returning 100 relays.

**Comment by juga0** [comment]
This is not the case anymore, every prioritizer loop returns around 300 relays, and we still consider one result at a time, since `results` are build without checking the fingerprint in the circuits.
Closed in favor of #29719 and #29720.This is not the case anymore, every prioritizer loop is
