### ISSUE TITLE
Unit tests not related with v3bw file header break when changing v3bw file header

### ISSUE THREAD

**Issue by juga0** [torproject/sbws#170]
proposed by #169.
Possibly other time measures.
@pastly since you coded this part and know it better, would be fine for you to fix it once #169 is merged?.

**Comment by teor2345** [comment]
Can you please explain this bug?

**Comment by pastly** [comment]
From what I'm gathering, the changes @teor2345 and @juga0 have been discussing are only about how times are printed in the v3bw file and what they are labeled. That has no affect on how freshness is calculated when determining relay measurement priority.

**Comment by juga0** [comment]
I changed the title of this issue since tests broken may not have to do anything with the timestamps nor the freshness.
However, i think that if when changing some part of the code affect to unit tests not related to that part, then either we need to refactor code or those unit tests are not unit tests.

**Comment by pastly** [comment]
I see now. Okay. Yes the unit tests need some love and attention.

**Comment by juga0** [comment]
The tests currently broken by issue169 branch are:
* https://github.com/pastly/simple-bw-scanner/compare/master...juga0:issue169?expand=1#diff-f8cd2c16d72d6b199edbe42c26e53671R76
* https://github.com/pastly/simple-bw-scanner/compare/master...juga0:issue169?expand=1#diff-dcea64797c457b7edf945e4bf3e04292R113
* https://github.com/pastly/simple-bw-scanner/compare/master...juga0:issue169?expand=1#diff-dcea64797c457b7edf945e4bf3e04292R147

**Comment by juga0** [comment]
They can be fixed after issue169 branch is merged

**Comment by pastly** [comment]
I wouldn't spend any more time trying to fix `tests/core/test_*.py`. They need overhauling, replacing, or removing.

**Comment by juga0** [comment]
Hmm, this issue is now marked as 1.0 (must), so you think we should fix the tests for a MVP?.
I think i should fix #197 first, since many tests would break again after that change. Should i also add #197 to 1.0 (must)?

**Comment by teor2345** [comment]
It seems like this issue was fixed in #225.
