### ISSUE TITLE
Choose 'fname' vs 'filepath' in config and update code accordingly

### ISSUE THREAD

**Issue by pastly** [torproject/sbws#189]
I'm looking [here](https://github.com/pastly/simple-bw-scanner/blob/9ac98afb626d795a4e0181b9a6038a0bd411a260/sbws/config.default.ini#L1) at the default config as it exists today.

I prefer `fname` and `dname`, personally.

And I guess this means I would have `datadir` become `data_dname`.

This is a minor thing.

**Comment by pastly** [comment]
If #236 is merged, that leaves `datadir` not fitting the naming convention.

**Comment by juga0** [comment]
Closed in favor of #29726
