### ISSUE TITLE
sbws should reset relay bandwidths when their IPv6 address changes

### ISSUE THREAD

**Issue by teor2345** [torproject/sbws#202]
Split off #154.

When IPv6 is more than a few percent of relay load, sbws should reset relay bandwidths on IPv6 address changes as well. (Tor doesn't measure IPv6 entry bandwidth separately, but we want to.)

Here's what we'd need to do:
1. Add a relay or_addresses attribute
2. Add or_addresses to result
3. Check any IPv6 addresses in or_addresses to see if they've changed

**Comment by juga0** [comment]
Moved to #29725
